<%
    const SETTING_EMAILTEMPLATE_PATH = "EmailTemplate_Path"
    const SETTING_EMAILTEMPLATE_CANCELLATION = "EmailTemplate_Cancellation"
    const SETTING_EMAILTEMPLATE_CONFIRMATION = "EmailTemplate_Confirmation"
    const SETTING_EMAILTEMPLATE_CONFLICT = "EmailTemplate_Conflict"
    const SETTING_EMAILTEMPLATE_INVITE = "EmailTemplate_Invite"
    const SETTING_EMAILTEMPLATE_PASSWORDRECOVERY = "EmailTemplate_PasswordRecovery"
    const SETTING_EMAILTEMPLATE_PAYMENTFAILED = "EmailTemplate_PaymentFailed"
    const SETTING_EMAILTEMPLATE_PAYMENTPENDING = "EmailTemplate_PaymentPending"
    const SETTING_EMAILTEMPLATE_REMINDER = "EmailTemplate_Reminder"
    const SETTING_EMAILTEMPLATE_SEARCHWAIVER = "EmailTemplate_SearchWaiver"
    const SETTING_EMAILTEMPLATE_WAIVER = "EmailTemplate_Waiver"
    const SETTING_EMAILTEMPLATE_WAIVERLOOKUP = "EmailTemplate_WaiverLookup"

    const SETTING_EMAILSUBJECT_CANCELLATION = "Email_Subject_Cancellation"
    const SETTING_EMAILSUBJECT_CONFIRMATION = "Email_Subject_Confirmation"
    const SETTING_EMAILSUBJECT_CONFLICT = "Email_Subject_Conflict"
    const SETTING_EMAILSUBJECT_INVITE = "Email_Subject_Invite"
    const SETTING_EMAILSUBJECT_PASSWORDRECOVERY = "Email_Subject_PasswordRecovery"
    const SETTING_EMAILSUBJECT_PAYMENTFAILED = "Email_Subject_PaymentFailed"
    const SETTING_EMAILSUBJECT_PAYMENTPENDING = "Email_Subject_PaymentPending"
    const SETTING_EMAILSUBJECT_REMINDER = "Email_Subject_Reminder"
    const SETTING_EMAILSUBJECT_SEARCHWAIVER = "Email_Subject_SearchWaiver"
    const SETTING_EMAILSUBJECT_WAIVER = "Email_Subject_Waiver"
    const SETTING_EMAILSUBJECT_WAIVERLOOKUP = "Email_Subject_WaiverLookup"
    
    const SETTING_EMAILTEMPLATE_FILE_HEADER = "EmailTemplate_File_Header"
    const SETTING_EMAILTEMPLATE_FILE_FOOTER = "EmailTemplate_File_Footer"
    const SETTING_EMAILTEMPLATE_FILE_CANCELLATION = "EmailTemplate_File_Cancellation"
    const SETTING_EMAILTEMPLATE_FILE_CONFIRMATION = "EmailTemplate_File_Confirmation"
    const SETTING_EMAILTEMPLATE_FILE_CONFLICT = "EmailTemplate_File_Conflict"
    const SETTING_EMAILTEMPLATE_FILE_CUSTOMFIELDLONG = "EmailTemplate_File_CustomFieldLong"
    const SETTING_EMAILTEMPLATE_FILE_CUSTOMFIELDSHORT = "EmailTemplate_File_CustomFieldShort"
    const SETTING_EMAILTEMPLATE_FILE_INVITE = "EmailTemplate_File_Invite"
    const SETTING_EMAILTEMPLATE_FILE_ORDERDETAILS = "EmailTemplate_File_OrderDetails"
    const SETTING_EMAILTEMPLATE_FILE_PASSWORDRECOVERY = "EmailTemplate_File_PasswordRecovery"
    const SETTING_EMAILTEMPLATE_FILE_PAYMENTFAILED = "EmailTemplate_File_PaymentFailed"
    const SETTING_EMAILTEMPLATE_FILE_PAYMENTPENDING = "EmailTemplate_File_PaymentPending"
    const SETTING_EMAILTEMPLATE_FILE_REMINDER = "EmailTemplate_File_Reminder"
    const SETTING_EMAILTEMPLATE_FILE_SEARCHWAIVER = "EmailTemplate_File_SearchWaiver"
    const SETTING_EMAILTEMPLATE_FILE_SIGNATURES = "EmailTemplate_File_Signatures"
    const SETTING_EMAILTEMPLATE_FILE_WAIVER = "EmailTemplate_File_Waiver"
    const SETTING_EMAILTEMPLATE_FILE_WAIVERLOOKUP = "EmailTemplate_File_WaiverLookup"

%>