<%
    const AVAILABLEDATE_COLUMN_DATE = "AvailableDate"
    const AVAILABLEDATE_COLUMN_STARTTIME = "StartTime"
    const AVAILABLEDATE_COLUMN_ENDTIME = "EndTime"

    const AVAILABLEDATE_INDEX_DATE = 0
    const AVAILABLEDATE_INDEX_STARTTIME = 1
    const AVAILABLEDATE_INDEX_ENDTIME = 2

    const AVAILABLEDATE_COLUMN_COUNT = 3
%>