<%
    const INVITATION_INDEX_ID = 0
    const INVITATION_INDEX_SITEGUID = 1
    const INVITATION_INDEX_EVENTID = 2
    const INVITATION_INDEX_NAME = 3
    const INVITATION_INDEX_EMAILADDRESS = 4
    const INVITATION_INDEX_INVITEDATETIME = 5
    const INVITATION_INDEX_RSVPCOUNT = 6
    const INVITATION_INDEX_RSVPDATETIME = 7
    const INVITATION_INDEX_RSVPSTATUS = 8
    const INVITATION_INDEX_COMMENTS = 9
    const INVITATION_INDEX_PUBLICCOMMENTS = 10
%>