<%
    const ORDERDETAIL_INDEX_EVENTID = 0
    const ORDERDETAIL_INDEX_LINENUMBER = 1
    const ORDERDETAIL_INDEX_ITEMNUMBER = 2
    const ORDERDETAIL_INDEX_ITEMDESCRIPTION = 3
    const ORDERDETAIL_INDEX_QUANTITY = 4
    const ORDERDETAIL_INDEX_PRICE = 5
    const ORDERDETAIL_INDEX_CREATEDATETIME = 6
    const ORDERDETAIL_INDEX_PAYMENTTRANSACTION = 7
    const ORDERDETAIL_INDEX_PAYMENTDATETIME = 8
    const ORDERDETAIL_INDEX_PAYMENTAMOUNT = 9
    const ORDERDETAIL_INDEX_ISADJUSTMENT = 10
%>