<%
    ' player constants
    CONST PLAYER_INDEX_PLAYERID = 0
    CONST PLAYER_INDEX_EMAILLIST = 1
    CONST PLAYER_INDEX_DATEOFBIRTH = 2
    CONST PLAYER_INDEX_STATE = 3
    CONST PLAYER_INDEX_ZIPCODE = 4
    CONST PLAYER_INDEX_PHONENUMBER = 5
    CONST PLAYER_INDEX_SITEGUID = 6
    CONST PLAYER_INDEX_FIRSTNAME = 7
    CONST PLAYER_INDEX_LASTNAME = 8
    CONST PLAYER_INDEX_CITY = 9
    CONST PLAYER_INDEX_ADDRESS = 10
    CONST PLAYER_INDEX_EMAILADDRESS = 11

%>
