<%
    ' playdatetime constants
    CONST PLAYDATETIME_INDEX_PLAYERID = 0
    CONST PLAYDATETIME_INDEX_PLAYDATE = 1
    CONST PLAYDATETIME_INDEX_PLAYTIME = 2
    CONST PLAYDATETIME_INDEX_EVENTID = 3
    CONST PLAYDATETIME_INDEX_CHECKINDATETIMEADMIN = 4

%>
