<%
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_ID = 0
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_SITEGUID = 1
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_NAME = 2
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_DATATYPE = 3
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_NOTES = 4
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_REQUIRED = 5
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_VALIDATE = 6
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_DEFAULTVALUE = 7
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_ADDITIONALINFO = 8
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_SEQUENCE = 9
    CONST   REGISTRATIONCUSTOMFIELD_INDEX_PAYMENTTYPE = 10
    
%>