<%
    const SCHEDULEDEVENTPAYMENT_INDEX_EVENTID = 0
    const SCHEDULEDEVENTPAYMENT_INDEX_STATUSDATETIME = 1
    const SCHEDULEDEVENTPAYMENT_INDEX_PAYMENTAMOUNT = 2
    const SCHEDULEDEVENTPAYMENT_INDEX_PAYMENTSTATUS = 3
    const SCHEDULEDEVENTPAYMENT_INDEX_PAYPALTRANSACTIONID = 4
%>