<%
    const USER_INDEX_SITEGUID = 0
    const USER_INDEX_USERNAME = 1
    const USER_INDEX_PASSWORD = 2
    const USER_INDEX_ROLEID = 3
    CONST USER_INDEX_EMAILADDRESS = 4
    CONST USER_INDEX_ENABLED = 5
    CONST USER_INDEX_PASSWORDEXPIRED = 6
    'const USER_INDEX_USERNAME = 0
    'const USER_INDEX_PASSWORD = 1
    'const USER_INDEX_ROLEID = 2
    'CONST USER_INDEX_EMAILADDRESS = 3
    'CONST USER_INDEX_ENABLED = 4
    'CONST USER_INDEX_PASSWORDEXPIRED = 5

%>