
<%
    const WAIVERLEGALESE_INDEX_LEGALESEID = 0
    const WAIVERLEGALESE_INDEX_ACTIVE = 1
    const WAIVERLEGALESE_INDEX_CREATEDDATETIME = 2
    const WAIVERLEGALESE_INDEX_POSTEDDATETIME = 3
    const WAIVERLEGALESE_INDEX_SITEGUID = 4
    const WAIVERLEGALESE_INDEX_LEGALESETEXT = 5


%>