<%
    CONST   WAIVERCUSTOMFIELD_INDEX_ID = 0
    CONST   WAIVERCUSTOMFIELD_INDEX_SITEGUID = 1
    CONST   WAIVERCUSTOMFIELD_INDEX_NAME = 2
    CONST   WAIVERCUSTOMFIELD_INDEX_DATATYPE = 3
    CONST   WAIVERCUSTOMFIELD_INDEX_NOTES = 4
    CONST   WAIVERCUSTOMFIELD_INDEX_REQUIRED = 5
    CONST   WAIVERCUSTOMFIELD_INDEX_VALIDATE = 6
    CONST   WAIVERCUSTOMFIELD_INDEX_DEFAULTVALUE = 7
    CONST   WAIVERCUSTOMFIELD_INDEX_FORMLOCATION = 9
    CONST   WAIVERCUSTOMFIELD_INDEX_ADDITIONALINFO = 10

%>