<%
    ' waiver2 constants
    const W2_COLUMN_INDEX_WAIVERID = 0
    CONST W2_COLUMN_INDEX_EXPORTED = 1
    CONST W2_COLUMN_INDEX_LEGALESEID = 2
    CONST W2_COLUMN_INDEX_PLAYERID = 3
    CONST W2_COLUMN_INDEX_PARENTID = 4
    CONST W2_COLUMN_INDEX_CREATEDATETIME = 5
    CONST W2_COLUMN_INDEX_STATE = 6
    CONST W2_COLUMN_INDEX_ZIPCODE = 7
    CONST W2_COLUMN_INDEX_PHONENUMBER = 8
    CONST W2_COLUMN_INDEX_HASHID = 9
    CONST W2_COLUMN_INDEX_SITEGUID = 10
    CONST W2_COLUMN_INDEX_SUBMITTEDFROMIPADDRESS = 11
    CONST W2_COLUMN_INDEX_CITY = 12
    CONST W2_COLUMN_INDEX_ADDRESS = 13
    CONST W2_COLUMN_INDEX_EMAILADDRESS = 14


    ' add new columns before the signatures because these fields
    ' are not used in the export functions
    CONST W2_COLUMN_INDEX_SIGNATURE = 15

    'waiver2 Export constants
   ' Only used for export
    const COLUMN_INDEX_WAIVERID = 0
    CONST COLUMN_INDEX_FIRSTNAME = 1
    CONST COLUMN_INDEX_LASTNAME = 2
    CONST COLUMN_INDEX_AGE = 3
    CONST COLUMN_INDEX_DATEOFBIRTH = 4
    CONST COLUMN_INDEX_PHONENUMBER = 5
    CONST COLUMN_INDEX_ADDRESS = 6
    CONST COLUMN_INDEX_CITY = 7
    CONST COLUMN_INDEX_STATE = 8
    CONST COLUMN_INDEX_ZIPCODE = 9
    CONST COLUMN_INDEX_PLAYDATE = 10
    CONST COLUMN_INDEX_WAIVERDATE = 11
    CONST COLUMN_INDEX_EMAILADDRESS = 12
    CONST COLUMN_INDEX_EMAILLIST = 13
    CONST COLUMN_INDEX_EVENTID = 14
    CONST COLUMN_INDEX_HASHID = 15
    CONST COLUMN_INDEX_PARENTFIRSTNAME = 16
    CONST COLUMN_INDEX_PARENTLASTNAME = 17
    CONST COLUMN_INDEX_PLAYTIME = 18
    CONST COLUMN_INDEX_SUBMITTEDFROMIPADDRESS = 19

    ' add new columns before the signatures because these fields
    ' are not used in the export functions
    CONST COLUMN_INDEX_PLAYERSIGNATURE = 20
    CONST COLUMN_INDEX_GUARDIANSIGNATURE = 21

    'only used during export
    CONST COLUMN_INDEX_CUSTOMFIELDS = 20

%>